### ISSUE TITLE
카테고리 조회

### ISSUE THREAD

**Issue by ju-ei8ht** [TripleA-Project/TripleA-BackEnd#15]
## Description

> 전체 카테고리, 관심 카테고리, 카테고리 검색 API

mainCategory값을 찾아서 이 mainCategory만 출력되어야 함(대분류)

## Tasks

- [x] 전체 카테고리 조회 API 완료
- [x] 관심 카테고리 조회 API 완료
- [x] Test Code 작성

## References

- [전체 카테고리 API](https://www.notion.so/5e8c68f1f09f4b5fa431035c38fe0fe1?pvs=4)
- [관심 카테고리 API](https://www.notion.so/716a9664f371407ba515d0a099d9b62f?pvs=4)
