### ISSUE TITLE
개인정보 조회 및 수정

### ISSUE THREAD

**Issue by ju-ei8ht** [TripleA-Project/TripleA-BackEnd#22]
## Description

> 개인정보 조회 및 수정

비밀번호는 출력이 안 됨.  
비밀번호를 변경하지 않는 경우는 password 및 newPassword 등을 empty로 받고.  
비밀번호를 변경하는 경우는 password가 조회한 password와 match하는지(인코더로) 확인하고 newPassword로 업데이트해야 함(메소드 쓰는 것을 권장)

## Tasks

- [ ] 개인정보 조회 API 완성
- [ ] 개인정보 수정 API 완성
- [ ] Test Code 작성

## References

- [개인정보 조회 API](https://www.notion.so/346ce740573f4773996d6206f7ccb25e?pvs=4)
- [개인정보 수정 API](https://www.notion.so/35d1d8c2d9964f3fa9d64916d3546841?pvs=4)
