### ISSUE TITLE
관심 카테고리 생성 및 삭제

### ISSUE THREAD

**Issue by ju-ei8ht** [TripleA-Project/TripleA-BackEnd#23]
## Description

> 관심 카테고리 생성 및 삭제

## Tasks

- [ ] 관심 카테고리 생성 API 완성
- [ ] 관심 카테고리 삭제 API 완성
- [ ] Test Code 작성

## References

- [관심 카테고리 생성 API](https://www.notion.so/a470c761eb7f42298570a1b55b4aeb36?pvs=4)
- [관심 카테고리 삭제 API](https://www.notion.so/e3b0cd2f7da4411499c1e8635a35afa8?pvs=4)
