### ISSUE TITLE
히스토리 뉴스

### ISSUE THREAD

**Issue by ju-ei8ht** [TripleA-Project/TripleA-BackEnd#24]
## Description

> 내가 본 뉴스, 북마크한 뉴스를 월별로 조회

내가 본 뉴스는 엔티티를 만들어서 Timestamped를 상속하고 user와 newsId를 가지고 있어야 함.  
그리고 뉴스 상세 조회 시에 historyNews가 save되어야 하는데 같은 날짜(LocalDateTIme.now로 확인하지 말고 ZonedDateTime으로 확인할 것 ZoneId는 Timestamped에 있음)에 save된 게 있다면 또 save하지 말고, 만약 다른 날이라면 같은 사용자여도 save되어야 함.  
북마크 뉴스는 createdAt 기준으로 조회하면 됨

## Tasks

- [x] 히스토리 뉴스, 북마크뉴스 조회 API 완성
- [x] 뉴스 상세보기 API에서 historyNews save 추가
- [x] Test Code 작성

## References

- [API](https://www.notion.so/003aba28b4dd4244a98b3dd44f1f909e?pvs=4)
