### ISSUE TITLE
주가 지수 조회

### ISSUE THREAD

**Issue by ju-ei8ht** [TripleA-Project/TripleA-BackEnd#45]
## Description

> 나스닥 종합지수, 다우존스 등 주가 지수 조회

야후 파이낸스에서 EST 기준 오후 5시 20분에 크롤링 및 Redis에 저장한 후 저장된 데이터를 API 호출 시 출력

## Tasks

- [x] 웹 크롤링 및 Redis 저장
- [x] 주가 지수 조회 API 완료
- [x] Test Code 작성

## References

- [야후 파이낸스](https://finance.yahoo.com)
- [API](https://www.notion.so/f533d5a8945944c380acf7ef4113de2a?pvs=4)
