### ISSUE TITLE
Entity ID 정책 변경, history query 수정

### ISSUE THREAD

**Issue by ju-ei8ht** [TripleA-Project/TripleA-BackEnd#64]
## Description

> Entity generatedType 변경(MySQL 문제), history의 날짜 조회 query -> native query로 수정

엔티티 ID GeneratedType을 IDENTITY로 했었는데 H2에서 테스트했을 땐 문제 없었는데 MySQL에서 테스트하니까
`could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement` 문제가 발생.   
ID를 AUTO로 바꾸니까 정상 작동해서 아예 문제가 발생하지 않도록 각 엔티티의 ID 값을 완전히 유니크하게(Sequence로) 관리하려고 합니다.   
그리고 history 저장 및 조회 시에 날짜별로 조회하려고 JPQL 쿼리를 썼었는데 이 역시 H2에서는 정상 작동하였으나 MySQL에서 문제가 발생해서 조회 및 저장이 되지 않아 query를 native query로 변경하였습니다.   
다른 분들도 혹시 모르니까 MySQL에서 정상 작동하는지 확인하시길 바랍니다.   
그리고 각 worker 메소드에 `@Transactional` 어노테이션을 붙여도 calling 메소드에 없으면 트랜잭션이 작동을 안 하더라고요. 그것도 혹시 다르게 하신 분들은 확인하세요...

## Tasks

- [x] Entity ID GeneratedType IDENTITY -> AUTO로 변경
- [x] history 및 bookmarkNews의 날짜로 조회하는 쿼리 -> 네이티브 쿼리로 수정
- [x] 관련된 test code 수정
- [x] worker 메소드에 `@Transactional` 제거하고 calling 메소드에 붙이기

## References

-
